### ISSUE TITLE
attribute options

### ISSUE THREAD

**Issue by Stanislav-Lapata** [ElMassimo/oj_serializers#18]
Our project has records with options fields
when I try use it as
```ruby
class SomeSerializer < Oj::Serializer
  attribute :options do
    # some code
  end 
end
```
I get options that I used in one/many

**Comment by ElMassimo** [comment]
In that case, the shorthand syntax detects the `options` method already exists, so it doesn't define it.

In this case, you would want to explicitly redefine the method:

```ruby
attribute def options
  # some code
end
```
